--- 
components: 
  schemas:
    Observation:
      description: 'Any measurment performed by a device is translated into an observtion with a specific type.'
      properties:
        id:
          anyOf:
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
          format: uri
          type: string
          description: "Unique identifier of the entity"
          x-ngsi:
            type: Property
        type:
          description: 'NGSI Entity type. It has to be Observation.'
          enum:
            - Observation
          type: string
          x-ngsi:
            type: Property
        measurementType:
          description: 'Anything that can be sensed, measured or controlled by. Enum: [connectedDevices, airPollution, atmosphericPressure, averageVelocity, batteryLife, batterySupply, cdom, conductance, conductivity, depth, eatingActivity, electricityConsumption, energy, fillingLevel, freeChlorine, gasConsumption, gateOpening, heading, humidity, light, location, milking, motion, movementActivity, noiseLevel, occupancy, orp, pH, power, precipitation, pressure, refractiveIndex, salinity, smoke, soilMoisture, solarRadiation, speed, tds, temperature, trafficFlow, tss, turbidity, waterConsumption, waterFlow, waterLevel, waterPollution, weatherConditions, weight, windDirection, windSpeed].'
          items:
            enum:
              - connectedDevices
              - airPollution
              - atmosphericPressure
              - averageVelocity
              - batteryLife
              - batterySupply
              - cdom
              - conductance
              - conductivity
              - depth
              - eatingActivity
              - electricityConsumption
              - energy
              - fillingLevel
              - freeChlorine
              - gasConsumption
              - gateOpening
              - heading
              - humidity
              - light
              - location
              - milking
              - motion
              - movementActivity
              - noiseLevel
              - occupancy
              - orp
              - pH
              - power
              - precipitation
              - pressure
              - refractiveIndex
              - salinity
              - smoke
              - soilMoisture
              - solarRadiation
              - speed
              - tds
              - temperature
              - trafficFlow
              - tss
              - turbidity
              - waterConsumption
              - waterFlow
              - waterLevel
              - waterPollution
              - weatherConditions
              - weight
              - windDirection
              - windSpeed
            type: string
          type: array
          x-ngsi:
            type: Property
        measurement:
          description: 'The performed measurment from the device.'
          type: string
          x-ngsi:
            type: Property
        valueType:
          description: 'The property that indicates whether the provided value is qualitative or measured. Enum: [Qualitative, Measured].'
          type: string
          enum:
            - Qualitative
            - Measured
          x-ngsi:
            type: Property
        description:
          description: 'The description of the specific observation.'
          type: string
          x-ngsi:
            type: Property
        dateModified:
          description: 'The date and time of this observation in ISO8601 UTC format.'
          format: date-time
          type: string
          x-ngsi:
            type: Property
        startDateTime:
          description: 'Reported start time corresponding to this observation.'
          format: date-time
          type: string
          x-ngsi:
            model: https://schema.org/DateTime
            type: Property
        precision:
          description: 'Accuracy granularity of the exposed value.'
          type: number
          maximum: 100
          minimum: 0
          x-ngsi:
            type: Property
        movementModifier:
          description: 'The modifier to the movement value (e.g. spin-90, left-20), units are device dependent.'    
          type: string    
          x-ngsi:    
            type: Property    
        movementSettings:
          description: 'The array of possible movement values.'    
          items:    
            type: string    
          type: array    
          x-ngsi:    
            type: Property
        openLevelValue:
          description: 'How open or ajar the entity is.'
          maximum: 100
          minimum: 0
          type: integer  
          x-ngsi:    
            type: Property
        units:
          description: 'The Resource Type.'
          enum:
            - F
            - C
            - K
          type: string
          x-ngsi:
            type: Property
        observationCategory:
          description: 'The category of the observation indicates if this observation is measured by a physical or virtual device. Enum: [VirtualObservation, PhysicalObservation].'
          enum:
            - Virtual
            - Physical
          type: string
          x-ngsi:
            type: Property
      required:
              - id
              - type
              - measurement
              - measurementType
      x-ngsi:
        uri-prefix: ""
info: 
  description: "Observation data model used within spaces"
  title: Observation
  version: "1.0.0"
openapi: "3.0.0"
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object